#!/bin/sh

runners=""
distdir="tests"

if test $# -gt 1; then

    distdir="$1"
    if test "x$2" = "xls"; then
        ls -1 $distdir/*_test
        exit 0
    fi

    shift 1
    runners="$@" 
    for runner in $runners; do
        make && sh tools/mkrunner.sh $distdir $runner
    done

elif test $# -eq 1; then

    if test "x$1" = "xls"; then
        ls -1 $distdir/*_test
        exit 0
    fi

    runners="$@"
    for runner in $runners; do
        make && sh tools/mkrunner.sh $distdir $runner
    done

else

    make && sh tools/mkrunner.sh $distdir

fi
