site_name: yana 
copyright: 'Copyright &copy; 2018 Guiquan Zhang'
site_author: Guiquan Zhang
site_url: http://www.yana.com
repo_url: https://github.com/yibit/yana

pages:
- 'Index': 'index.md'
- 'API':
  - 'Index': 'index.md'

#theme: material 
theme_dir: themes/material
docs_dir: ../docs
edit_url: edit/master/docs
site_dir: _site
extra_css:
  - 'assets/stylesheets/extra.css'
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
    - js/umlconvert.js

extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
#  logo: img/logo.png
  social:
    - type: github
      link: https://github.com/yana
    - type: twitter
      link: https://twitter.com/yana
    - type: facebook
      link: https://facebook.com/yana

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.superfences

